[2024-10-05T21:13:00.040+0700] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-05T21:13:00.061+0700] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: talend_job_dag_Sync_Mysql_to_DWh_job.run_talend_job manual__2024-10-05T14:12:56.655152+00:00 [queued]>
[2024-10-05T21:13:00.073+0700] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: talend_job_dag_Sync_Mysql_to_DWh_job.run_talend_job manual__2024-10-05T14:12:56.655152+00:00 [queued]>
[2024-10-05T21:13:00.074+0700] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-05T21:13:00.099+0700] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): run_talend_job> on 2024-10-05 14:12:56.655152+00:00
[2024-10-05T21:13:00.106+0700] {standard_task_runner.py:72} INFO - Started process 255516 to run task
[2024-10-05T21:13:00.117+0700] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'talend_job_dag_Sync_Mysql_to_DWh_job', 'run_talend_job', 'manual__2024-10-05T14:12:56.655152+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/Sync_Mysql_to_DWh_job.py', '--cfg-path', '/tmp/tmpigzlzih2']
[2024-10-05T21:13:00.119+0700] {standard_task_runner.py:105} INFO - Job 40: Subtask run_talend_job
[2024-10-05T21:13:00.222+0700] {task_command.py:467} INFO - Running <TaskInstance: talend_job_dag_Sync_Mysql_to_DWh_job.run_talend_job manual__2024-10-05T14:12:56.655152+00:00 [running]> on host linux-ip-147
[2024-10-05T21:13:00.354+0700] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='talend_job_dag_Sync_Mysql_to_DWh_job' AIRFLOW_CTX_TASK_ID='run_talend_job' AIRFLOW_CTX_EXECUTION_DATE='2024-10-05T14:12:56.655152+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-05T14:12:56.655152+00:00'
[2024-10-05T21:13:00.357+0700] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-05T21:13:00.358+0700] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-05T21:13:00.358+0700] {logging_mixin.py:190} INFO - Current task name:run_talend_job state:running start_date:2024-10-05 14:13:00.061872+00:00
[2024-10-05T21:13:00.359+0700] {logging_mixin.py:190} INFO - Dag name:talend_job_dag_Sync_Mysql_to_DWh_job and current dag run status:running
[2024-10-05T21:13:00.359+0700] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-05T21:13:00.361+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-05T21:13:00.363+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '"sh /opt/Sync_Mysql_to_DWH_Job/run_Sync_Mysql_to_DWH_job.sh"']
[2024-10-05T21:13:00.374+0700] {subprocess.py:86} INFO - Output:
[2024-10-05T21:13:00.377+0700] {subprocess.py:93} INFO - /usr/bin/bash: line 1: sh /opt/Sync_Mysql_to_DWH_Job/run_Sync_Mysql_to_DWH_job.sh: No such file or directory
[2024-10-05T21:13:00.378+0700] {subprocess.py:97} INFO - Command exited with return code 127
[2024-10-05T21:13:00.395+0700] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/usr/local/lib/python3.10/dist-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-10-05T21:13:00.412+0700] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-05T21:13:00.412+0700] {logging_mixin.py:190} INFO - Task start:2024-10-05 14:13:00.061872+00:00 end:2024-10-05 14:13:00.410431+00:00 duration:0.348559
[2024-10-05T21:13:00.413+0700] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): run_talend_job> dag:<DAG: talend_job_dag_Sync_Mysql_to_DWh_job> dagrun:<DagRun talend_job_dag_Sync_Mysql_to_DWh_job @ 2024-10-05 14:12:56.655152+00:00: manual__2024-10-05T14:12:56.655152+00:00, state:running, queued_at: 2024-10-05 14:12:56.683192+00:00. externally triggered: True>
[2024-10-05T21:13:00.414+0700] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 127.
[2024-10-05T21:13:00.414+0700] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=talend_job_dag_Sync_Mysql_to_DWh_job, task_id=run_talend_job, run_id=manual__2024-10-05T14:12:56.655152+00:00, execution_date=20241005T141256, start_date=20241005T141300, end_date=20241005T141300
[2024-10-05T21:13:00.446+0700] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-05T21:13:00.447+0700] {standard_task_runner.py:124} ERROR - Failed to execute job 40 for task run_talend_job (Bash command failed. The command returned a non-zero exit code 127.; 255516)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.10/dist-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/usr/local/lib/python3.10/dist-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/usr/local/lib/python3.10/dist-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/usr/local/lib/python3.10/dist-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/usr/local/lib/python3.10/dist-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-10-05T21:13:00.494+0700] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-05T21:13:00.538+0700] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-05T21:13:00.540+0700] {local_task_job_runner.py:245} INFO - ::endgroup::
